name: React Docker S2I
description: Build and push React Docker image

inputs:
  registry:
    description: Docker registry
    required: true
  username:
    description: Registry username
    required: true
  password:
    description: Registry password
    required: true
  image_name:
    description: Docker image name
    required: true
  tag:
    description: Docker image tag
    required: false
    default: latest
  api-base-url:
    description: Vite API base URL
    required: false

runs:
  using: "composite"
  steps:
    - name: Run S2I Script
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_REGISTRY: ${{ inputs.registry }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_IMAGE_NAME: ${{ inputs.image_name }}
        INPUT_TAG: ${{ inputs.tag }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}