name: React Docker S2I
description: Build and push React Docker image

inputs:
  registry:
    description: Docker registry
    required: true
  username:
    description: Registry username
    required: true
  password:
    description: Registry password
    required: true
  image-name:
    description: Docker image name
    required: true
  tag:
    description: Docker image tag
    required: false
    default: latest

outputs:
  image_name:
    description: Full image name

runs:
  using: docker
  image: Dockerfile.react
