FROM node:18 AS build

WORKDIR /app

# 👇 نستقبل المتغير
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY . .

RUN npm install
RUN npm run build

# ------------------------

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
